'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MainSpecs
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''txtSearchText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lstSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstSearchResults As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''Table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''txtProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMain_Code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMain_Code As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCorrelating_IMPS_Number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorrelating_IMPS_Number As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtGTIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGTIN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtGradeBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGradeBrand As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtGrade_Abbreviation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGrade_Abbreviation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCut_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCut_Type As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProduct_Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProduct_Description As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProduct_Description_Alpha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProduct_Description_Alpha As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProduct_DescriptionAlpha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProduct_DescriptionAlpha As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label14 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtBox_Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBox_Description As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMixed_Combo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMixed_Combo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPrimary_Bag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrimary_Bag As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSecondary_Bag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSecondary_Bag As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSpecial_Packaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpecial_Packaging As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProduct_Film_WholeTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProduct_Film_WholeTop As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProduct_Film_Bottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProduct_Film_Bottom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSpecial_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpecial_Label As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSpecial_Label_Description_Box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpecial_Label_Description_Box As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSpecial_Label_Description_Package control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpecial_Label_Description_Package As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSticker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSticker As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPrimary_Sticker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrimary_Sticker As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSecondary_Sticker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSecondary_Sticker As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPattiesPackage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPattiesPackage As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPackagesBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackagesBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChubsBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChubsBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPcBag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPcBag As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBagBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBagBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPcBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPcBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHdBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHdBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtApproximate_PiecesCombo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApproximate_PiecesCombo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtApproximate_HeadCombo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApproximate_HeadCombo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtWeight_Classification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeight_Classification As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtGross_Wt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGross_Wt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNet_Wt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNet_Wt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPiece_Gross_WtLbs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPiece_Gross_WtLbs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPiece_Net_WtLbs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPiece_Net_WtLbs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBox_Gross_WtLbs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBox_Gross_WtLbs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBox_Net_WtLbs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBox_Net_WtLbs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtApproximate_Box_Gross_WtLbs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApproximate_Box_Gross_WtLbs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtApproximate_Box_Net_WtLbs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApproximate_Box_Net_WtLbs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtApproximate_Combo_Gross_WtLbs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApproximate_Combo_Gross_WtLbs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtApproximate_Combo_Net_WtLbs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApproximate_Combo_Net_WtLbs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBoxID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBoxID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPrimary_BagId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrimary_BagId As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSecondary_BagID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSecondary_BagID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDTS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMicrobial_Testing_Required control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMicrobial_Testing_Required As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBy_Product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBy_Product As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRaw_MaterialProduct_Derived_From control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRaw_MaterialProduct_Derived_From As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFat_Percentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFat_Percentage As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLean_Percentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLean_Percentage As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInitial_Grind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInitial_Grind As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFinal_Grind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFinal_Grind As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtGrind_Classification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGrind_Classification As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPatty_Classification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPatty_Classification As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label13 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDomestic_Shelf_Life_Fresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDomestic_Shelf_Life_Fresh As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDomestic_Shelf_Life_Frozen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDomestic_Shelf_Life_Frozen As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtExport_Shelf_Life_Fresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExport_Shelf_Life_Fresh As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtExport_Shelf_LifeFrozen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExport_Shelf_LifeFrozen As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Table2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table2 As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''Label12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label12 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnAddProductImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddProductImage As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Label17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label17 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgPrimaryPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPrimaryPhoto As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''Label18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label18 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgSecondaryPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSecondaryPhoto As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''Label19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label19 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgBoxWeightLabelPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBoxWeightLabelPhoto As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''Label20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label20 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgBoxLabelPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBoxLabelPhoto As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''trAdd1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAdd1 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgAdditional1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAdditional1 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''trAdd2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAdd2 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgAdditional2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAdditional2 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''trAdd3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAdd3 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgAdditional3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAdditional3 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''trAdd4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAdd4 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgAdditional4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAdditional4 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''trAdd5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAdd5 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgAdditional5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAdditional5 As Global.System.Web.UI.WebControls.Image
End Class
