<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="Pictures.aspx.vb" Inherits="ProductSpecs.Pictures" %>

<!DOCTYPE html>


<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>GOP Product Specification Form</title>
    <link rel="stylesheet" href="GOPStyles.css"/>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <h1>Greater Omaha Product Specification Picture Update Form</h1> 
        </div>
        
        <div id="DIVDIVDIV">     
            <asp:Table ID="tableInfo" runat="server" Width="50%" BorderStyle="Groove" Font-Bold="True" Font-Size="Large">
                <asp:TableRow >
                    <asp:TableCell Width="45%"><asp:Label ID="Label1" runat="server" Text="Product Code: "></asp:Label></asp:TableCell>
                    <asp:TableCell Width="55%"><asp:Label ID="lblProductCode" runat="server"></asp:Label></asp:TableCell>
                </asp:TableRow>
                <asp:TableRow>
                    <asp:TableCell><asp:Label ID="Label3" runat="server" Text="Product Name: "></asp:Label></asp:TableCell>
                    <asp:TableCell><asp:Label ID="lblProductName" runat="server"></asp:Label></asp:TableCell>
                </asp:TableRow>
            </asp:Table>

            <br />
            <br />
            <br />
            <br />
            <asp:Table ID="uploadTable" runat="server" Width="50%" BorderStyle="Groove" Font-Bold="True" Font-Size="Large">
                <asp:TableRow >
                    <asp:TableCell Width="70%">Choose a photo to be attached to this product.<br /><br /><asp:FileUpload ID="FileUpload1" runat="server" /></asp:TableCell>
                    <asp:TableCell Width="30%" HorizontalAlign="Center"><asp:Button runat="server" Text="Upload Photo" ID="Button1" OnClick="UploadFile"/></asp:TableCell>
                </asp:TableRow>
                <asp:TableRow>
                    <asp:TableCell><asp:Label ID="lblMessage" runat="server"></asp:Label></asp:TableCell>
                </asp:TableRow>
            </asp:Table>

            <br />
            <br />

            <asp:Table ID="updateInfo" runat="server" Width="50%" BorderStyle="Groove" Font-Bold="True" Font-Size="Large">
                <asp:TableRow >
                    <asp:TableCell Width="70%">Update or select picture choices as needed.<br /><br />Only one picture can be associated with a selection per item.</asp:TableCell>
                    <asp:TableCell Width="30%" HorizontalAlign="Center"><asp:Button runat="server" id="btnUpdateSelection" onclick="btnUpdateSelection_Click" text="Update Selection" /><br /><br />
                    <asp:LinkButton runat="server"><a href="javascript: history.go(-1)">Go Back</a></asp:LinkButton></asp:TableCell>
                </asp:TableRow>
            </asp:Table>

            <br />
            <br />
            <br />
            <asp:Table runat="server" ID="tableImages" Borderwidth="3" BorderStyle="Solid">
<asp:TableRow ID="tr1"><asp:TableCell ID="tc1_1" BorderWidth="2"><asp:Label runat="server" ID="l1"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary1" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" id="secondary1" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" id="additional1" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" id="boxweightlabel1" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" id="boxlabel1" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" id="archive1" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc1_2" BorderWidth="2"><asp:Image runat="server" ID="image1" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr2"><asp:TableCell ID="tc2_1" BorderWidth="2"><asp:Label runat="server" ID="l2"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary2" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary2" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional2" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel2" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel2" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive2" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc2_2" BorderWidth="2"><asp:Image runat="server" ID="image2" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr3"><asp:TableCell ID="tc3_1" BorderWidth="2"><asp:Label runat="server" ID="l3"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary3" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary3" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional3" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel3" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel3" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive3" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc3_2" BorderWidth="2"><asp:Image runat="server" ID="image3" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr4"><asp:TableCell ID="tc4_1" BorderWidth="2"><asp:Label runat="server" ID="l4"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary4" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary4" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional4" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel4" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel4" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive4" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc4_2" BorderWidth="2"><asp:Image runat="server" ID="image4" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr5"><asp:TableCell ID="tc5_1" BorderWidth="2"><asp:Label runat="server" ID="l5"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary5" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary5" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional5" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel5" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel5" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive5" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc5_2" BorderWidth="2"><asp:Image runat="server" ID="image5" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr6"><asp:TableCell ID="tc6_1" BorderWidth="2"><asp:Label runat="server" ID="l6"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary6" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary6" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional6" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel6" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel6" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive6" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc6_2" BorderWidth="2"><asp:Image runat="server" ID="image6" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr7"><asp:TableCell ID="tc7_1" BorderWidth="2"><asp:Label runat="server" ID="l7"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary7" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary7" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional7" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel7" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel7" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive7" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc7_2" BorderWidth="2"><asp:Image runat="server" ID="image7" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr8"><asp:TableCell ID="tc8_1" BorderWidth="2"><asp:Label runat="server" ID="l8"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary8" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary8" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional8" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel8" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel8" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive8" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc8_2" BorderWidth="2"><asp:Image runat="server" ID="image8" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr9"><asp:TableCell ID="tc9_1" BorderWidth="2"><asp:Label runat="server" ID="l9"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary9" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary9" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional9" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel9" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel9" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive9" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc9_2" BorderWidth="2"><asp:Image runat="server" ID="image9" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr10"><asp:TableCell ID="tc10_1" BorderWidth="2"><asp:Label runat="server" ID="l10"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary10" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary10" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional10" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel10" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel10" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive10" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc10_2" BorderWidth="2"><asp:Image runat="server" ID="image10" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr11"><asp:TableCell ID="tc11_1" BorderWidth="2"><asp:Label runat="server" ID="l11"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary11" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary11" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional11" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel11" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel11" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive11" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc11_2" BorderWidth="2"><asp:Image runat="server" ID="image11" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr12"><asp:TableCell ID="tc12_1" BorderWidth="2"><asp:Label runat="server" ID="l12"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary12" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary12" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional12" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel12" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel12" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive12" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc12_2" BorderWidth="2"><asp:Image runat="server" ID="image12" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr13"><asp:TableCell ID="tc13_1" BorderWidth="2"><asp:Label runat="server" ID="l13"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary13" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary13" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional13" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel13" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel13" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive13" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc13_2" BorderWidth="2"><asp:Image runat="server" ID="image13" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr14"><asp:TableCell ID="tc14_1" BorderWidth="2"><asp:Label runat="server" ID="l14"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary14" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary14" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional14" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel14" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel14" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive14" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc14_2" BorderWidth="2"><asp:Image runat="server" ID="image14" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr15"><asp:TableCell ID="tc15_1" BorderWidth="2"><asp:Label runat="server" ID="l15"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary15" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary15" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional15" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel15" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel15" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive15" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc15_2" BorderWidth="2"><asp:Image runat="server" ID="image15" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr16"><asp:TableCell ID="tc16_1" BorderWidth="2"><asp:Label runat="server" ID="l16"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary16" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary16" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional16" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel16" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel16" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive16" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc16_2" BorderWidth="2"><asp:Image runat="server" ID="image16" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr17"><asp:TableCell ID="tc17_1" BorderWidth="2"><asp:Label runat="server" ID="l17"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary17" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary17" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional17" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel17" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel17" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive17" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc17_2" BorderWidth="2"><asp:Image runat="server" ID="image17" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr18"><asp:TableCell ID="tc18_1" BorderWidth="2"><asp:Label runat="server" ID="l18"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary18" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary18" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional18" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel18" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel18" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive18" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc18_2" BorderWidth="2"><asp:Image runat="server" ID="image18" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr19"><asp:TableCell ID="tc19_1" BorderWidth="2"><asp:Label runat="server" ID="l19"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary19" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary19" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional19" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel19" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel19" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive19" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc19_2" BorderWidth="2"><asp:Image runat="server" ID="image19" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr20"><asp:TableCell ID="tc20_1" BorderWidth="2"><asp:Label runat="server" ID="l20"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary20" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary20" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional20" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel20" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel20" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive20" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc20_2" BorderWidth="2"><asp:Image runat="server" ID="image20" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr21"><asp:TableCell ID="tc21_1" BorderWidth="2"><asp:Label runat="server" ID="l21"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary21" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary21" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional21" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel21" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel21" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive21" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc21_2" BorderWidth="2"><asp:Image runat="server" ID="image21" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr22"><asp:TableCell ID="tc22_1" BorderWidth="2"><asp:Label runat="server" ID="l22"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary22" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary22" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional22" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel22" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel22" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive22" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc22_2" BorderWidth="2"><asp:Image runat="server" ID="image22" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr23"><asp:TableCell ID="tc23_1" BorderWidth="2"><asp:Label runat="server" ID="l23"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary23" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary23" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional23" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel23" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel23" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive23" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc23_2" BorderWidth="2"><asp:Image runat="server" ID="image23" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr24"><asp:TableCell ID="tc24_1" BorderWidth="2"><asp:Label runat="server" ID="l24"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary24" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary24" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional24" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel24" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel24" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive24" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc24_2" BorderWidth="2"><asp:Image runat="server" ID="image24" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr25"><asp:TableCell ID="tc25_1" BorderWidth="2"><asp:Label runat="server" ID="l25"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary25" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary25" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional25" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel25" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel25" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive25" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc25_2" BorderWidth="2"><asp:Image runat="server" ID="image25" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr26"><asp:TableCell ID="tc26_1" BorderWidth="2"><asp:Label runat="server" ID="l26"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary26" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary26" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional26" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel26" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel26" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive26" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc26_2" BorderWidth="2"><asp:Image runat="server" ID="image26" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr27"><asp:TableCell ID="tc27_1" BorderWidth="2"><asp:Label runat="server" ID="l27"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary27" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary27" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional27" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel27" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel27" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive27" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc27_2" BorderWidth="2"><asp:Image runat="server" ID="image27" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr28"><asp:TableCell ID="tc28_1" BorderWidth="2"><asp:Label runat="server" ID="l28"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary28" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary28" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional28" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel28" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel28" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive28" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc28_2" BorderWidth="2"><asp:Image runat="server" ID="image28" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr29"><asp:TableCell ID="tc29_1" BorderWidth="2"><asp:Label runat="server" ID="l29"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary29" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary29" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional29" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel29" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel29" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive29" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc29_2" BorderWidth="2"><asp:Image runat="server" ID="image29" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr30"><asp:TableCell ID="tc30_1" BorderWidth="2"><asp:Label runat="server" ID="l30"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary30" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary30" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional30" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel30" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel30" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive30" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc30_2" BorderWidth="2"><asp:Image runat="server" ID="image30" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr31"><asp:TableCell ID="tc31_1" BorderWidth="2"><asp:Label runat="server" ID="l31"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary31" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary31" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional31" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel31" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel31" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive31" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc31_2" BorderWidth="2"><asp:Image runat="server" ID="image31" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr32"><asp:TableCell ID="tc32_1" BorderWidth="2"><asp:Label runat="server" ID="l32"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary32" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary32" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional32" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel32" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel32" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive32" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc32_2" BorderWidth="2"><asp:Image runat="server" ID="image32" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr33"><asp:TableCell ID="tc33_1" BorderWidth="2"><asp:Label runat="server" ID="l33"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary33" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary33" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional33" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel33" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel33" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive33" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc33_2" BorderWidth="2"><asp:Image runat="server" ID="image33" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr34"><asp:TableCell ID="tc34_1" BorderWidth="2"><asp:Label runat="server" ID="l34"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary34" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary34" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional34" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel34" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel34" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive34" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc34_2" BorderWidth="2"><asp:Image runat="server" ID="image34" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr35"><asp:TableCell ID="tc35_1" BorderWidth="2"><asp:Label runat="server" ID="l35"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary35" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary35" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional35" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel35" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel35" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive35" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc35_2" BorderWidth="2"><asp:Image runat="server" ID="image35" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr36"><asp:TableCell ID="tc36_1" BorderWidth="2"><asp:Label runat="server" ID="l36"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary36" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary36" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional36" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel36" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel36" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive36" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc36_2" BorderWidth="2"><asp:Image runat="server" ID="image36" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr37"><asp:TableCell ID="tc37_1" BorderWidth="2"><asp:Label runat="server" ID="l37"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary37" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary37" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional37" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel37" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel37" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive37" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc37_2" BorderWidth="2"><asp:Image runat="server" ID="image37" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr38"><asp:TableCell ID="tc38_1" BorderWidth="2"><asp:Label runat="server" ID="l38"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary38" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary38" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional38" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel38" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel38" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive38" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc38_2" BorderWidth="2"><asp:Image runat="server" ID="image38" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr39"><asp:TableCell ID="tc39_1" BorderWidth="2"><asp:Label runat="server" ID="l39"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary39" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary39" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional39" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel39" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel39" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive39" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc39_2" BorderWidth="2"><asp:Image runat="server" ID="image39" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr40"><asp:TableCell ID="tc40_1" BorderWidth="2"><asp:Label runat="server" ID="l40"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary40" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary40" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional40" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel40" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel40" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive40" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc40_2" BorderWidth="2"><asp:Image runat="server" ID="image40" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr41"><asp:TableCell ID="tc41_1" BorderWidth="2"><asp:Label runat="server" ID="l41"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary41" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary41" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional41" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel41" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel41" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive41" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc41_2" BorderWidth="2"><asp:Image runat="server" ID="image41" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr42"><asp:TableCell ID="tc42_1" BorderWidth="2"><asp:Label runat="server" ID="l42"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary42" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary42" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional42" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel42" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel42" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive42" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc42_2" BorderWidth="2"><asp:Image runat="server" ID="image42" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr43"><asp:TableCell ID="tc43_1" BorderWidth="2"><asp:Label runat="server" ID="l43"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary43" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary43" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional43" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel43" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel43" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive43" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc43_2" BorderWidth="2"><asp:Image runat="server" ID="image43" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr44"><asp:TableCell ID="tc44_1" BorderWidth="2"><asp:Label runat="server" ID="l44"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary44" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary44" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional44" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel44" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel44" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive44" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc44_2" BorderWidth="2"><asp:Image runat="server" ID="image44" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr45"><asp:TableCell ID="tc45_1" BorderWidth="2"><asp:Label runat="server" ID="l45"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary45" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary45" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional45" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel45" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel45" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive45" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc45_2" BorderWidth="2"><asp:Image runat="server" ID="image45" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr46"><asp:TableCell ID="tc46_1" BorderWidth="2"><asp:Label runat="server" ID="l46"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary46" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary46" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional46" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel46" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel46" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive46" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc46_2" BorderWidth="2"><asp:Image runat="server" ID="image46" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr47"><asp:TableCell ID="tc47_1" BorderWidth="2"><asp:Label runat="server" ID="l47"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary47" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary47" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional47" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel47" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel47" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive47" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc47_2" BorderWidth="2"><asp:Image runat="server" ID="image47" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr48"><asp:TableCell ID="tc48_1" BorderWidth="2"><asp:Label runat="server" ID="l48"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary48" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary48" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional48" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel48" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel48" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive48" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc48_2" BorderWidth="2"><asp:Image runat="server" ID="image48" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr49"><asp:TableCell ID="tc49_1" BorderWidth="2"><asp:Label runat="server" ID="l49"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary49" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary49" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional49" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel49" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel49" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive49" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc49_2" BorderWidth="2"><asp:Image runat="server" ID="image49" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>
<asp:TableRow ID="tr50"><asp:TableCell ID="tc50_1" BorderWidth="2"><asp:Label runat="server" ID="l50"></asp:Label><br /><br /><asp:CheckBox runat="server" ID="primary50" Text="Primary Photo"/><br /><br /><asp:CheckBox runat="server" ID="secondary50" Text="Secondary Photo"/><br /><br /><asp:CheckBox runat="server" ID="additional50" Text="Additional Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxweightlabel50" Text="Box Weight Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="boxlabel50" Text="Box Label Photo"/><br /><br /><asp:CheckBox runat="server" ID="archive50" Text="Archive Photo"/></asp:TableCell><asp:TableCell ID="tc50_2" BorderWidth="2"><asp:Image runat="server" ID="image50" AlternateText="Image Here"/></asp:TableCell></asp:TableRow>



            </asp:Table>

        </div>
    </form>
</body>
</html>
